import {StyleSheet} from 'react-native';
import {ms} from 'react-native-size-matters';

export const styles = StyleSheet.create({
  global: {flex: 1, backgroundColor: '#f2f2f2'},
  flatlist: {marginTop: ms(28), marginLeft: ms(8)},
  containerContent: {marginBottom: ms(24)},
  imgContent: {
    height: ms(240),
    width: ms(172),
    alignSelf: 'center',
    borderTopLeftRadius: ms(10),
    borderTopRightRadius: ms(10),
    marginLeft: ms(6),
  },
  content: {
    height: ms(158),
    width: ms(172),
    alignSelf: 'center',
    borderBottomRightRadius: ms(10),
    borderBottomLeftRadius: ms(10),
    marginLeft: ms(6),
    backgroundColor: 'white',
  },
  allGame: {marginLeft: ms(16), marginTop: ms(28)},
  containerGenre: {
    flexDirection: 'row',
    marginLeft: ms(12),
    alignItems: 'center',
  },
  genre: {
    backgroundColor: '#202020',
    borderColor: 'white',
    height: ms(28),
    width: ms(72),
    borderWidth: ms(1),
    borderRadius: ms(6),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: ms(20),
    marginRight: ms(10),
  },
  containerRate: {
    backgroundColor: '#202020',
    borderColor: '#f3ad2e',
    borderWidth: ms(2),
    marginLeft: ms(112),
    borderRadius: ms(6),
    height: ms(32),
    width: ms(42),
    alignContent: 'center',
    justifyContent: 'center',
    marginTop: ms(12),
  },
  txtTitle: {
    color: 'black',
    fontWeight: '600',
    fontSize: ms(28),
    marginLeft: ms(12),
    marginTop: ms(12),
  },
  show: {
    backgroundColor: '#202020',
    borderWidth: ms(2),
    borderColor: 'white',
    height: ms(36),
    width: ms(96),
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: ms(16),
    borderRadius: ms(8),
  },
});
